---
# Action Repo: https://github.com/actions/starter-workflows

name: Greetings

# yamllint disable-line rule:truthy
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            Thank you for logging your first issue in our repository.
            We shall review and revert in due course. In the interim feel free to Use the Dojo.
          pr-message: >
            Thank you for submitting your first PR to our repository.
            We shall review and revert in due course. In the interim feel free to Use the Dojo.
