---
name: Spell Check - Workflow
# Trigger the workflow on push to any branch except master
on:
  push:
jobs:
  spell-check:
    name: markdown spell check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Spelling check via PySpelling
        uses: sbates130272/spellcheck-github-actions@v0.7.0
